### ISSUE TITLE
Compile issue on Mac OS X

### ISSUE THREAD

**Issue by subu-cliqz** [ruud-v-a/filebuffer#2] opened 2016-10-17 18:23 UTC
Tried with rustc 1.12.0 on OSX 10.11.2

```
error[E0308]: mismatched types
  --> /Users/subu/.cargo/registry/src/github.com-1ecc6299db9ec823/filebuffer-0.1.0/src/unix.rs:58:60
   |
58 |         libc::mincore(buffer as *mut libc::c_void, length, residency_uchar)
   |                                                            ^^^^^^^^^^^^^^^ expected i8, found u8

```

**Comment by ruuda** [comment] 2016-10-17 20:02
Thanks for reporting! What target triple are you using? `x86_64-apple-darwin`? It looks like `libc::mincore` takes a `*mut c_char` there, unlike the `x86_64-unknown-linux-gnu` version which takes a `*mut c_uchar`. This should be easy to fix with some conditional compilation, I’ll have a look shortly.

**Comment by ruuda** [comment] 2016-10-22 21:20
Sorry for the delay. I have a fix in the `macos` branch that at least passes the tests on Travis. Could you please verify that it works for you? If it does then I’ll upload a new release to crates.io.

**Comment by cmbrandenburg** [comment] 2017-08-03 12:19
I confirmed that the `macos` branch indeed fixes this error on MacOS (rustc 1.19.0, MacOS 10.12.6). The crate compiles ok, and all tests pass.

I tested this by merging the `master` branch into the `macos` branch. There's a trivial conflict in `.travis.yml`.

Is anything else preventing this fix from getting merged in and uploaded to crates.io?

**Comment by ruuda** [comment] 2017-08-03 16:44
The fix is already on master, I just haven’t published a new version to crates.io yet. I’ll publish it right away.

**Comment by ruuda** [comment] 2017-08-03 17:04
Version 0.3.0, which includes the fix, is now on crates.io.

**Closed as completed by ruuda** 2017-08-03 17:04 UTC
